### ISSUE TITLE
solr_wrapper is not starting

### ISSUE THREAD

**Issue by dutr5288** [cbeer/solr_wrapper#131]
Hi,
I am trying to run the command in my project: 

` solr_wrapper --config .solr_wrapper
`

However, i got the error below : 

```
Starting Solr 6.0.0 on port 8983 ... Traceback (most recent call last):
	10: from /Users/users/.rbenv/versions/2.6.3/bin/solr_wrapper:23:in `<main>'
	 9: from /Users/users/.rbenv/versions/2.6.3/bin/solr_wrapper:23:in `load'
	 8: from /Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.1.0/exe/solr_wrapper:113:in `<top (required)>'
	 7: from /Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:64:in `wrap'
	 6: from /Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.1.0/exe/solr_wrapper:114:in `block in <top (required)>'
	 5: from /Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:215:in `with_collection'
	 4: from /Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:151:in `create'
	 3: from /Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	 2: from /Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 1: from /Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
/Users/users/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:152:in `block in create': Not started yet (RuntimeError)
```

My version information : 
```
Ruby -v : ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]
Rails -v : 5.1.7
solr_wrapper version : v2.1.0
which solr_wrapper : /Users/users/.rbenv/shims/solr_wrapper
Device: MacOS Mojave - 10.14.6 (18G103)
Java -v : openjdk 12.0.2 2019-07-16
```

I had no clue about what is going on on my laptop. It ran perfectly fine on one of my co-worker machine.
However, my co-worker installed those package several months ago. We were trying to compare the version and all things.
We are not sure if is there anything wrong with our environment variable, version incompatible.

Appreciate for any suggestion or clue.
Thanks,

**Comment by dutr5288** [comment]
I found the problem. 
Java version should be on 1.8. 
After i downgraded my java version to be 1.8 and its fixed the issue.

All good now. Thank you.
