### ISSUE TITLE
Unexpected error not caught

### ISSUE THREAD

**Issue by mark-dce** [cbeer/solr_wrapper#25]
When I ran `solr_wrapper -p 8983 -d solr/config/ --collection_name hydra-development`

I got the error
```
Starting Solr 5.4.1 on port 8983 ...                                                                                   /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/progress.rb:58:in `progress=': You can't set the item's current value to be greater than the total. (ProgressBar::InvalidProgressError)
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/base.rb:156:in `block in update_progress'
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:38:in `with_refresh'
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/base.rb:155:in `update_progress'
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/base.rb:99:in `progress='
	from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/solr_wrapper-0.5.1/lib/solr_wrapper/instance.rb:403:in `block in fetch_with_progressbar'
```

**Comment by jcoyne** [comment]
@cbeer are you still working on this?  I hit it again today.
